### PR TITLE
adding bad path tests

### PR DESCRIPTION
**Pull request by shireenf-ibm**
base PR: #380
issue #444
coverage is full on paths we can cover

### CODE REVIEW

**Review by adisos — COMMENTED** [review]
are the errors printed to log through `ca.logger.Errorf` ?
through which function?

**Comment by shireenf-ibm** [comment]
> are the errors printed to log through `ca.logger.Errorf` ? through which function?

errors are returned to the calling funcs in 'connlist' and printed there.  ( the logger is added to `eval` pkg in the #447 for `warnings` logging need)

**Comment by adisos** [comment]
> > are the errors printed to log through `ca.logger.Errorf` ? through which function?
> 
> errors are returned to the calling funcs in `connlist` and handled there. ( the logger is added to `eval` pkg in the #447 for `warnings` logging need)

which function?

**Comment by shireenf-ibm** [comment]
> > > are the errors printed to log through `ca.logger.Errorf` ? through which function?
> > 
> > 
> > errors are returned to the calling funcs in `connlist` and handled there. ( the logger is added to `eval` pkg in the #447 for `warnings` logging need)
> 
> which function?

I think errors which are returned from `eval` pkg are considered `fatal` in `connlist` and returned as `error` in the main calling funcs i.e. "connlist API" .

(this is our way to return errors from `eval` pkg to `connlist` pkg till now (same done before supporting the ANPs) - the 'error handling system' was not changed/ touched in this PR (nor any other PR that is related to ANP))

however, the calls in `connlist` pkg to `eval (policy-engine)` funcs that may return `error` in this PR are :
 1. `err := pe.AddObjectsForExposureAnalysis(objectsList)` in  `getPolicyEngine`  -> errors to be returned finally by the connlist API funcs `ConnlistFromDirPath` or `ConnlistFromResourceInfos`
 2. `pe.AllAllowedConnectionsBetweenWorkloadPeers` which is in `getConnectionsBetweenPeers` and same here the error will be finally returned by the connlist API funcs `ConnlistFromDirPath` or `ConnlistFromResourceInfos`

**Review by adisos — APPROVED** [review]

**Review by adisos — APPROVED** [review]

**Pull request merged**
