### PR TITLE
Peer as interface

### PR DESCRIPTION
**Pull request by adisos**
Handle issue #49 (change Peer type to an interface for package eval) + #50 (use eval.Peer interface instead of redefining a peer interface).

### CODE REVIEW

**Comment by zivnevo** [comment]
I'm a bit confused. Can you please explain why we need 2 `Peer` interfaces? Why can't we just have the one in `eval`?

**Comment by adisos** [comment]
> 

We need the Peer interface to be used internally at internal/k8s pkg and to be exposed externally by the eval pkg.
The interface for internal pkg is different from the interface of the eval pkg.
The eval.Peer interface should not have all methods of the k8s.Peer interface.
The internal interface is to handle issue #49 - convert Peer struct to Peer interface, and is used at netpol analysis.
The eval.Peer interface is to expose a Peer outside the eval pkg, such as connlist, and as the objects returned from eval.GetPeersList.

**Review by zivnevo — APPROVED** [review]
You might want to consider moving some of the code in `eval/check.go` to `internal/k8s/peer.go`, e.g., `isPodToItself()` and `isPeerNodeIP()`. Ideally, eval should work on a more abstract level.

Also, note that some of the files (e.g., `ipBlock.go` are missing the license header. Maybe open a separate issue for this.

**Comment by adisos** [comment]
> You might want to consider moving some of the `k8s.Peer`-related code in `eval/check.go` to `internal/k8s/peer.go`, e.g., `isPodToItself()` and `isPeerNodeIP()`. Ideally, eval should work on a more abstract level.
> 
> Also, note that some of the files (e.g., `ipBlock.go`) are missing the license header. Maybe open a separate issue for this.

Added these comments to a separate issue.

**Pull request merged**
